language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'

before_script:
   - composer install

script: phpunit --coverage-clover=coverage.clover ./tests

notifications:
  email: false
  irc:
    channels:
       secure: "Am2Se+OxqD7wlfN6xSJbB8pV5D9uJorcRCzGAsJkYCXjNdmZKV06XKD2RElIxukCl91I0IY8Ln1OpM8pApMTy+CEfFpBRvTFySzmpVdBNeSTuSEJaUNffEYTFFFVj6hqReDLW8Bw1/f6FGClhWrrOJhl0SkCIeyUb9FfsqrlD0M="
    on_success: change
    on_failure: always

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover


sudo: false
